trigger:
- main

schedules:
  - cron: 0 0 * * *
    branches:
      include:
        - main
    displayName: Every Monday at 0:00 am UTC
    always: true

variables:
  - name: image_publisher
    value: "MicrosoftWindowsDesktop"
  - name: image_offer
    value: "office-365"
  - name: image_sku
    value: "win11-21h2-avd-m365"
  - name: image_latest_version
    
stages:
  - stage: Environment Preparation
    jobs:
      - job: install_required_software
        displayName: Install Docker, Azure CLI, Terraform
        steps:
          - task: Bash@3
            displayName: Install Docker
            inputs:
              targetType: 'inline'
              script: |
                sudo apt update
                   sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
                   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                   sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
                   sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
                   sudo apt update
                   apt-cache policy docker-ce
                   sudo apt install docker-ce -y
                   sudo systemctl start docker
          - task: Bash@3
            displayName: Install Azure CLI
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get update 
                   sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg -y
                   curl -sL https://packages.microsoft.com/keys/microsoft.asc |
                       gpg --dearmor |
                       sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
                   AZ_REPO=$(lsb_release -cs)
                   echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
                       sudo tee /etc/apt/sources.list.d/azure-cli.list
                   sudo apt-get update
                   sudo apt-get install azure-cli -y
                   sudo apt install unzip -y

          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
          
          - task: Bash@3
            displayName: Pulling TFSec, TFlint and InfraCost docker images
            inputs:
              targetType: 'inline'
              script: |
                # TFSEC
                sudo docker pull tfsec/tfsec:v1.13.2-arm64v8
                   
                # TFLINT
                sudo docker pull ghcr.io/terraform-linters/tflint:v0.35.0
                
                # InfraCost
                sudo docker pull infracost/infracost:0.9

      - job: get_latest_windows_version
        displayName: Get latest windows version using azure cli
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Enterprise: BizSpark(e1412e0d-6593-4f7c-839d-0f264e2e6772)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                latest_version=$(
                  az vm image show \
                    --urn "${IMAGE_PUBLISHER}:${IMAGE_OFFER}:${IMAGE_SKU}:latest" \
                    --query name \
                    --out tsv
                )
                
                echo "Publisher: ${IMAGE_PUBLISHER}"
                echo "Offer:     ${IMAGE_OFFER}"
                echo "SKU:       ${IMAGE_SKU}"
                echo "Version:   ${latest_version}"

    
